version : 0.0.3
container-name-run : "todoserver-swift-run"
container-name-tools : "todoserver-swift-tools"
image-name-run : "todoserver-swiftrun"
image-name-tools: "todoserver-swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile"
build-cmd-debug : "/root/utils/tools-utils.sh build debug"
debug-cmd : "/root/utils/tools-utils.sh debug todoServer 1024"
build-cmd-run : "/root/utils/tools-utils.sh build release"
run-cmd : "/root/utils/run-utils.sh run todoServer"
test-cmd : "/root/utils/tools-utils.sh test"
container-path-run : "/root/project"
container-path-tools : "/root/project"
container-port-map : "8080:8080"
container-port-map-debug : "2048:1024,2049:1025"
